package cn.bjhdltcdn.p2plive.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Transient;

/**
 * Entity mapped to table "PROPS".
 */
@Entity
public class Props implements Parcelable {
    //主键自增类型必须是大写Long
    @Id(autoincrement = false)
    private long propsId;

    private String name;
    private int type;
    private int price;//道具价格,
    private String url;//图片路径,
    private String duration;//使用时长(道具类型使用),
    private String descrption;//描述(道具类型使用),
    private int salePrice;//打折价格,
    private int isSale;//是否打折 0 不打折 1 打折,
    private int giftType;//礼物类型(1--->普通礼物，2--->多人视频房间礼物),
    private String animatedUrl;//动画效果图图片路径,


    /***********显示特效需要*start************/
    // uid + giftid 拼起来组成一个唯一标识
    @Transient
    private String generateId;
    //推送礼物url
    @Transient
    private String propUrl;
    //推送礼物name
    @Transient
    private String propsName;
    //推送礼物数量
    @Transient
    private int giftMultiple;
    @Transient
    private int goldNum;
    // 是否被选中
    @Transient
    private boolean isSelected;

    /***********显示特效需要*start************/
    public long getPropsId() {
        return propsId;
    }

    public void setPropsId(long propsId) {
        this.propsId = propsId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public int getPrice() {
        return price;
    }

    public void setPrice(int price) {
        this.price = price;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getDuration() {
        return duration;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

    public String getDescrption() {
        return descrption;
    }

    public void setDescrption(String descrption) {
        this.descrption = descrption;
    }

    public int getSalePrice() {
        return salePrice;
    }

    public void setSalePrice(int salePrice) {
        this.salePrice = salePrice;
    }

    public int getIsSale() {
        return isSale;
    }

    public void setIsSale(int isSale) {
        this.isSale = isSale;
    }

    public int getGiftType() {
        return giftType;
    }

    public void setGiftType(int giftType) {
        this.giftType = giftType;
    }

    public String getAnimatedUrl() {
        return animatedUrl;
    }

    public void setAnimatedUrl(String animatedUrl) {
        this.animatedUrl = animatedUrl;
    }

    public String getGenerateId() {
        return generateId;
    }

    public void setGenerateId(String generateId) {
        this.generateId = generateId;
    }

    public String getPropUrl() {
        return propUrl;
    }

    public void setPropUrl(String propUrl) {
        this.propUrl = propUrl;
    }

    public String getPropsName() {
        return propsName;
    }

    public void setPropsName(String propsName) {
        this.propsName = propsName;
    }

    public boolean isSelected() {
        return isSelected;
    }

    public void setSelected(boolean selected) {
        isSelected = selected;
    }

    public int getGiftMultiple() {
        return giftMultiple;
    }

    public void setGiftMultiple(int giftMultiple) {
        this.giftMultiple = giftMultiple;
    }

    public int getGoldNum() {
        return goldNum;
    }

    public void setGoldNum(int goldNum) {
        this.goldNum = goldNum;
    }

    public Props() {
    }

    @Generated(hash = 2087700812)
    public Props(long propsId, String name, int type, int price, String url, String duration, String descrption, int salePrice, int isSale, int giftType,
                 String animatedUrl) {
        this.propsId = propsId;
        this.name = name;
        this.type = type;
        this.price = price;
        this.url = url;
        this.duration = duration;
        this.descrption = descrption;
        this.salePrice = salePrice;
        this.isSale = isSale;
        this.giftType = giftType;
        this.animatedUrl = animatedUrl;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeLong(this.propsId);
        dest.writeString(this.name);
        dest.writeInt(this.type);
        dest.writeInt(this.price);
        dest.writeString(this.url);
        dest.writeString(this.duration);
        dest.writeString(this.descrption);
        dest.writeInt(this.salePrice);
        dest.writeInt(this.isSale);
        dest.writeInt(this.giftType);
        dest.writeString(this.animatedUrl);
        dest.writeString(this.generateId);
        dest.writeString(this.propUrl);
        dest.writeString(this.propsName);
        dest.writeInt(this.giftMultiple);
        dest.writeInt(this.goldNum);
        dest.writeByte(this.isSelected ? (byte) 1 : (byte) 0);
    }

    protected Props(Parcel in) {
        this.propsId = in.readLong();
        this.name = in.readString();
        this.type = in.readInt();
        this.price = in.readInt();
        this.url = in.readString();
        this.duration = in.readString();
        this.descrption = in.readString();
        this.salePrice = in.readInt();
        this.isSale = in.readInt();
        this.giftType = in.readInt();
        this.animatedUrl = in.readString();
        this.generateId = in.readString();
        this.propUrl = in.readString();
        this.propsName = in.readString();
        this.giftMultiple = in.readInt();
        this.goldNum = in.readInt();
        this.isSelected = in.readByte() != 0;
    }

    public static final Creator<Props> CREATOR = new Creator<Props>() {
        @Override
        public Props createFromParcel(Parcel source) {
            return new Props(source);
        }

        @Override
        public Props[] newArray(int size) {
            return new Props[size];
        }
    };
}
