package cn.bjhdltcdn.p2plive.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.bjhdltcdn.p2plive.model.PlaceOrderMessage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PLACE_ORDER_MESSAGE".
*/
public class PlaceOrderMessageDao extends AbstractDao<PlaceOrderMessage, String> {

    public static final String TABLENAME = "PLACE_ORDER_MESSAGE";

    /**
     * Properties of entity PlaceOrderMessage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property UserIdAndStoreId = new Property(0, String.class, "userIdAndStoreId", true, "USER_ID_AND_STORE_ID");
    }


    public PlaceOrderMessageDao(DaoConfig config) {
        super(config);
    }
    
    public PlaceOrderMessageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PLACE_ORDER_MESSAGE\" (" + //
                "\"USER_ID_AND_STORE_ID\" TEXT PRIMARY KEY NOT NULL );"); // 0: userIdAndStoreId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PLACE_ORDER_MESSAGE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PlaceOrderMessage entity) {
        stmt.clearBindings();
 
        String userIdAndStoreId = entity.getUserIdAndStoreId();
        if (userIdAndStoreId != null) {
            stmt.bindString(1, userIdAndStoreId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PlaceOrderMessage entity) {
        stmt.clearBindings();
 
        String userIdAndStoreId = entity.getUserIdAndStoreId();
        if (userIdAndStoreId != null) {
            stmt.bindString(1, userIdAndStoreId);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public PlaceOrderMessage readEntity(Cursor cursor, int offset) {
        PlaceOrderMessage entity = new PlaceOrderMessage( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // userIdAndStoreId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PlaceOrderMessage entity, int offset) {
        entity.setUserIdAndStoreId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final String updateKeyAfterInsert(PlaceOrderMessage entity, long rowId) {
        return entity.getUserIdAndStoreId();
    }
    
    @Override
    public String getKey(PlaceOrderMessage entity) {
        if(entity != null) {
            return entity.getUserIdAndStoreId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PlaceOrderMessage entity) {
        return entity.getUserIdAndStoreId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
